mod common;
mod document;
mod endpoint;
mod r#enum;
mod field_option;
mod fieldset;
mod namespace;
mod operation;
mod service;
mod r#struct;
mod r#type;
mod value;

pub use common::Span;
pub use document::{parse_document, Document};
pub use endpoint::Endpoint;
pub use field_option::FieldOption;
pub use fieldset::{Field as FieldsetField, Fieldset};
pub use namespace::{Namespace, NamespacePart};
pub use operation::Operation;
pub use r#enum::Enum;
pub use r#struct::{Field, Struct};
pub use r#type::Type;
pub use service::{Service, ServiceEndpoint};
pub use value::Value;